#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🛠️ Styling your project before committing 🛠️'
echo 'Please wait, this may take a while...'

# Check eslint standard and run tests
pnpm lint || {
  echo '💀 Oops.. you have a problem with your code 💀'
  echo 'Fix it first, then commit it again'
  false
}

pnpm ci:test || {
  echo '💀 Oops.. you have a problem with your test code 💀'
  echo 'Fix it first, then commit it again'
  false
}

echo '✅ No error found: you can commit your code now 🚀🚀'
